[project]
name = "nba-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastparquet>=2024.5.0",
    "nba-api>=1.6.0",
    "pandas>=2.2.3",
    "pyarrow>=17.0.0",
]
