name: Deploy data to gh-pages
on:
  workflow_dispatch:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .gz copies to signal non-compressibility
        run: |
          # Workaround for GitHub Pages CDN bug: when serving range requests,
          # the CDN tries to serve byte slices of cached, gzipped assets. This
          # fails because the range is not a valid gzip stream. By creating
          # copies with .gz appended, we signal that files are already
          # compressed, preventing the CDN from attempting compression.
          #
          # https://github.com/orgs/community/discussions/178318
          find ./data -type f ! -name "*.gz" -exec sh -c 'cp "$1" "$1.gz"' _ {} \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./data
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-spaces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to DigitalOcean Spaces
        run: |
          aws s3 sync ./data s3://nba-data \
            --endpoint-url https://nyc3.digitaloceanspaces.com \
            --acl public-read \
            --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}
