name: Get data from nba.com

on:
  workflow_dispatch:
  schedule:
    # every hour on the 11th minute
    - cron: "11 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Download NBA data
        run: python dl.py
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
