name: Get data from nba.com

on:
  workflow_dispatch:
  schedule:
    # every hour on the 11th minute
    - cron: "11 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      # cache thingy taken from
      # https://gist.github.com/alukach/6f3a371e9af600e417aca1b36806ad72
      # no idea if it actually works or what, but let's try
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Download NBA data
        run: pipenv run python dl.py
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
